### ISSUE TITLE
environment variable to sharp install scripts

### ISSUE THREAD

**Issue by kachkaev** [lovell/sharp#1182]
I'm using sharp in a TypeScript project, which gets built inside GitLab CI. The pipeline consists of two jobs:
* `build-app`: lint code, run some unit tests, convert TypeScript to JavaScript
* `build-image`: grab JavaScript from the first build, install production npm dependencies and  produce a docker image with all these files

Because I'm not using any `sharp` functionality in the first job, waiting for it to be built is kind of useless. There is a way to skip this by running `yarn --ignore-scripts` instead of `yarn`, however, this flag may break other things.

I'm wondering if there a space for some env flag like `SHARP_SKIP_INSTALL`. It would be useful when someone is not planning to call `sharp` methods, but still wants to have it in project dependencies so that linting etc. passes. If such a flag is added, I'd be able to use `SHARP_SKIP_INSTALL=true yarn` inside my first CI job  instead of `yarn --ignore-scripts` and thus be sure I did not break anything with `--ignore-scripts`, yet run the build in a nice tiny alpine image.

WDYT?

**Comment by lovell** [comment]
Hello, I would share `node_modules` between the jobs. Install everything in the first job then take advantage of yarn's ability to prune non-production dependencies in the second job.

build-app:
```sh
yarn install
```
build-image:
```sh
yarn install --production --ignore-scripts --prefer-offline
```

**Comment by kachkaev** [comment]
Thanks for your suggestion @lovell. The problem with this approach is that I have to change the base docker image in which the first job runs. The entire pipeline looks like this now:

```yaml
stages:
  - build-app
  - build-image

build app:
  stage: build-app
  image: node:9.10.1-alpine
  script:
    - yarn --ignore-scripts # do not build npm module "sharp"
    - yarn lint
    - yarn test
    - yarn build
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - build
    expire_in: 1 day

build image:
  stage: build-image
  image: docker:latest
  services:
   - docker:dind
  script:
    - docker info
    - echo $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG || docker pull $CI_REGISTRY_IMAGE:master || true
    - docker build --pull --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --shm-size 256M .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
```

The `Dockerfile` that's used in the second job is:

```dockerfile
FROM node:9.10.1-alpine

# prepare for npm module "sharp"
RUN apk add --no-cache \
    build-base \
 && apk add --no-cache --repository https://dl-3.alpinelinux.org/alpine/edge/testing/ \
    vips-dev \
    fftw-dev

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
RUN YARN_CACHE_FOLDER=/dev/shm/yarn_cache yarn --production

COPY build /usr/src/app/build

EXPOSE 4000

USER node

CMD [ "yarn", "graphql:prod" ]
```

All is fine except that I'm afraid to disable too much with `--ignore-scripts` one day.

To be able to install `sharp` in the first job properly, I'd have to change the base image in which CI is executed. The main reason why I prefer to stick with `node:x.x.x-alpine` here is because I don't want to lag behind node releases, which seems to be the case for all three community-maintained [`sharp` docker images](https://github.com/lovell/sharp/blob/master/docs/install.md#docker). If I add `apk add` to job one like in Dockerfile, it'll slow down.

So here's what I'd like to do in `.gitlab-ci.yml`:

```yaml
build app:
  stage: build-app
  image: node:9.10.1-alpine
  script:
    - SHARP_SKIP_INSTALL=true yarn  # <-------- 👀 
    - yarn lint
    - yarn test
    - yarn build
# ...
```
