### ISSUE TITLE
Module initialization error on using Sharp in AWS lambda functions

### ISSUE THREAD

**Issue by mysteron** [lovell/sharp#1197]
Hi,

I'm using a Windows machine and try to deploy my Lambda function using serverless. I followed the instruction: https://github.com/lovell/sharp/blob/master/docs/install.md#aws-lambda

I'm using node 6.10 and webpack.

Here's my webpack config:

```javascript
// webpack.config.js
const path = require('path');
const slsw = require('serverless-webpack');


module.exports = {
  mode: "development",
  entry: slsw.lib.entries,
  resolve: {
    extensions: [
      '.js',
      '.json',
      '.ts',
      '.tsx'
    ]
  },
  externals: ["sharp"],
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js'
  },
  target: 'node',
  module: {
    rules: [
      {
        test: /\.ts(x?)$/,
        use: [
          {
            loader: 'ts-loader'
          }
        ],
      }
    ]
  }
};
```

And here's the part of serverless.yml that configures the webpack:

```yaml
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    packager: 'npm'   # Reserved for future use. Any other values will not work right now.
    packExternalModulesMaxBuffer: 200 * 1024   # Size of stdio buffers for spawned child processes
```

The error I'm getting is the following:
```
module initialization error: Error
at Error (native)
at Object.Module._extensions..node (module.js:597:18)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/node_modules/sharp/lib/constructor.js:9:15)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
```

What am I doing wrong? I'd appreciate any hints...

**Comment by lovell** [comment]
Hello, is `npm install` run inside the `lambci/lambda:build-nodejs6.10` Linux container as the instructions suggest (and, more importantly, not on the Windows host itself)?

**Comment by mysteron** [comment]
Yes, I think so. I run docker deamon (Docker for Windows), I have my drives shared, and then run this command:

```console
docker run -v /d/my-project-path:/var/task lambci/lambda:build-nodejs6.10 npm install
```

**Comment by mysteron** [comment]
I would say: definatel yes, becasue when I try to run the code that uses Sharp locally I get this error:
```console
Error: %1 is not a valid Win32 application.
```

**Comment by lovell** [comment]
Are you using the Lambda Node.js 6.10 runtime (and not the 8.10 runtime)?

**Comment by mysteron** [comment]
Yes:

```yaml
provider:
  name: aws
  runtime: nodejs6.10
```
