### ISSUE TITLE
Kubernetes resource limits

### ISSUE THREAD

**Issue by gajus** [lovell/sharp#2281]
I am trying to understand what is the correct value to use for Kubernetes pod resource limits.

Kubernetes documentation says:

> Limits and requests for CPU resources are measured in cpu units. One cpu, in Kubernetes, is equivalent to 1 vCPU/Core for cloud providers [..]
> CPU is always requested as an absolute quantity, never as a relative quantity; 0.1 is the same amount of CPU on a single-core, dual-core, or 48-core machine.

– https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-cpu

Meanwhile, I am on a 8 core machine and my configuration is:

```yaml
resources:
  requests:
    memory: '1Gi'
    cpu: '50m'
  limits:
    memory: '4Gi'
    cpu: '2000m'

```

However, if I check `sharp.concurrency()`, it says that it is using 8 threads. Should I limit concurrency to 2, since Kubernetes resource limit is 2 cores?
