### ISSUE TITLE
Can't install on linux/arm64 with docker node

### ISSUE THREAD

**Issue by gpetrov** [lovell/sharp#2482]
Trying to run a simple Dockerfile to install node together with sharp on linux/arm64 fails.

```Dockerfile
FROM node:14-slim

RUN npm i detect-libc

RUN node -e "console.log('platform=' + process.platform);console.log('arch='+process.arch);console.log(require('detect-libc'))"

RUN npm i sharp
```

when ran on arm64 - it produces:

```
> [4/4] RUN npm i sharp:                                                                                                                                                                                     
#8 3.664                                                                                                                                                                                                      
#8 3.664 > sharp@0.26.3 install /node_modules/sharp                                                                                                                                                           
#8 3.664 > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)                                                                                 
#8 3.664                                                                                                                                                                                                      
#8 3.736 ERR! sharp Use with glibc 2.24 requires manual installation of libvips >= 8.10.0
#8 3.736 info sharp Attempting to build from source via node-gyp but this may fail due to the above error
#8 3.736 info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
#8 3.789 gyp ERR! find Python 
```

while the arch checks gives:
```
platform=linux
arch=arm64
{
  GLIBC: 'glibc',
  MUSL: 'musl',
  family: 'glibc',
  version: '2.24',
  method: 'getconf',
  isNonGlibcLinux: false
}
```

There are already prebuild libvips images for arm64v8 - why aren't they used?

Running the same on Windows 10, goes actually just fine. While the arch checks is there pretty much the same:

```
Step 3/4 : RUN node -e "console.log('platform=' + process.platform);console.log('arch='+process.arch);console.log(require('detect-libc'))"
 ---> Running in 4c7db816aa17
platform=linux
arch=x64
{
  GLIBC: 'glibc',
  MUSL: 'musl',
  family: 'glibc',
  version: '2.24',
  method: 'getconf',
  isNonGlibcLinux: false
}
Removing intermediate container 4c7db816aa17
 ---> 68c8b2d9c3f4
Step 4/4 : RUN npm i sharp
 ---> Running in a617bbed12e4

> sharp@0.26.3 install /node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-linux-x64.tar.br

+ sharp@0.26.3
added 73 packages from 173 contributors and audited 74 packages in 7.417s
```

@lovell  I think the glibc check is a bit too hard and doesn't check for prebuild images first.

**Comment by lovell** [comment]
Hi, the salient part is:

> ERR! sharp Use with glibc 2.24 requires manual installation of libvips >= 8.10.0

This is documented at https://sharp.pixelplumbing.com/install#prebuilt-binaries

> Ready-compiled sharp and libvips binaries are provided for use with Node.js v10+ on the most common platforms:
> ...
> Linux ARM64 (glibc >= 2.29)

> The following platforms require compilation of both libvips and sharp from source:
> ...
> Linux ARM64 (glibc <= 2.28, musl)

**Comment by gpetrov** [comment]
But there is no need to compile anything...?

docker image is linux/arm64 and there is a prebuild binary available.

it runs all fine in linux/x86 - while there is the same glibc 2.24

or does node needs to change all their official docker image to include glibc 2.29+ ?

**Comment by lovell** [comment]
Please see https://github.com/lovell/sharp-libvips/commit/2e4202d671904666c012b142b8e21be017d30a28 for a discussion about why the prebuilt arm64 binaries currently require glibc 2.29+

**Comment by gpetrov** [comment]
Thanks - make sense now. Hope node updates their base images. However even latest buster image is still with glibc 2.28

Maybe you can consider to support musc? Trying node-14-alpine, prodced:

```
> sharp@0.26.3 install /node_modules/sharp                                                                                                                                                           
#8 3.650 > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)                                                                                 
#8 3.650                                                                                                                                                                                                      
#8 3.758 info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-linuxmusl-arm64v8.tar.br
#8 4.032 ERR! sharp Prebuilt libvips 8.10.0 binaries are not yet available for linuxmusl-arm64v8
```

**Comment by gpetrov** [comment]
Btw the Linux/arm64 is running natively on the new Apple Silicon M1 arm64 with the upcoming Docker Desktop version for the M1.

So it is essential to have the right binaries ready for easy docker deploy @lovell

**Comment by gpetrov** [comment]
can you clarify @lovell that you need GLIBC 2.29+ - just to run libvips? Not only to compile it?

**Comment by lovell** [comment]
As you hopefully saw from the discussion in https://github.com/lovell/sharp-libvips/commit/2e4202d671904666c012b142b8e21be017d30a28, gcc 9.2.0+ is required to compile libvips on arm64 without introducing compiler bugs. The oldest OS that provides gcc 9.2.0 is Debian 11, which also provides and therefore requires glibc 2.29.

**Comment by gpetrov** [comment]
Yes I saw that - but I don't need to compile libvips - the precompiled binary from sharp-libvips for arm64v8 is just fine!
https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-linux-arm64v8.tar.gz

But your check for glibc version prevents it for being downloaded....

**Comment by lovell** [comment]
A binary compiled on Debian 11 will require glibc 2.29+ at runtime.

**Comment by gpetrov** [comment]
ok then we will have to wait for node to be available on debian bullseye ... it might take a while.

maybe there is a better hope for node-alpine with musl?

**Comment by lovell** [comment]
> we will have to wait for node to be available on debian bullseye 

https://packages.debian.org/bullseye/nodejs

**Comment by gpetrov** [comment]
I mean the official docker node image:

https://hub.docker.com/_/node

It doesn't have bullseye yet, so no docker node installation under arm64 can run sharp ...

**Comment by gpetrov** [comment]
See also:

https://github.com/nodejs/docker-node/issues/1415

**Comment by lovell** [comment]
Let's track this at https://github.com/lovell/sharp-libvips/issues/72

**Comment by gpetrov** [comment]
@lovell are the node-gyp checks already adjusted for the new live builds? I'm still getting errors of not found binaries.
Also on the regular linux/arm64 - the gcc version check is still in place:

Using node-14:slim (GCC)

```
#13 19.60 npm ERR! path /opt/node_app/node_modules/sharp
#13 19.60 npm ERR! command failed
#13 19.60 npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
#13 19.60 npm ERR! ERR! sharp Use with glibc 2.24 requires manual installation of libvips >= 8.10.5
#13 19.60 npm ERR! info sharp Attempting to build from source via node-gyp but this may fail due to the above error
```

and using node-14:alpine (MUSL)

```
#12 19.17 npm ERR! path /opt/node_app/node_modules/sharp
#12 19.17 npm ERR! command failed
#12 19.17 npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
#12 19.17 npm ERR! info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-linuxmusl-arm64v8.tar.br
#12 19.17 npm ERR! ERR! sharp Prebuilt libvips 8.10.5 binaries are not yet available for linuxmusl-arm64v8
#12 19.17 npm ERR! info sharp Attempting to build from source via node-gyp but this may fail due to the above error
```

**Comment by lovell** [comment]
@gpetrov The `linuxmusl-arm64v8` binaries will be made available from sharp v0.28.0+ and will require musl >= 1.1.24 (the `linux-arm64v8` binaries will still require glibc >= 2.29).

**Comment by gpetrov** [comment]
ah bummer 😃  well lets hope 0.28 come soon then.

Yes node-14:slim uses unfortunately Debian Buster with glibc 2.28, so no much luck there. I thought you were able to lower that requirement with cross compiling?

Lets hope for the node-14:alpine that can use Alpine 3.13 having musl 1.2

**Comment by lovell** [comment]
> Debian Buster with glibc 2.28, so no much luck there. I thought you were able to lower that requirement with cross compiling?

No, sorry, I did some more digging and gcc 9 is required - see https://github.com/lovell/sharp-libvips/pull/86#issuecomment-774747302

**Comment by gpetrov** [comment]
Correction node-14:slim uses even Debian Stretch with glibc 2.24
We can target specific node-14:buster-slim that uses Debian Buster with glibc 2.28 but that is the max for now as described in: https://github.com/nodejs/docker-node/issues/1415

**Comment by Amila-Rukshan** [comment]
I'm also facing the same issue where sharp is a transitive dependency in the [gatsby blog theme](https://github.com/willjw3/gatsby-starter-developer-diary). 
`npm ERR! ERR! sharp Use with glibc 2.28 requires manual installation of libvips >= 8.10.5`
I'm going to deploy this on [raspberry Pi 4](https://www.raspberrypi.com/products/raspberry-pi-4-model-b/specifications/) which is ARM v8 - 64 bit. And I'm doing the building in github actions as platform set to linux/arm64.
Following is the Dockerfile I have.
```
FROM node:16.4.2 as builder

WORKDIR /app

COPY package.json .
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

FROM nginx
EXPOSE 80
COPY --from=builder /app/public /usr/share/nginx/html
```
Github action
```
name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - 
        name: Install libvips
        run: sudo apt-get update -y && sudo apt-get install -y libvips
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dev-diary:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/dev-diary:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/dev-diary:buildcache,mode=max
```
