### ISSUE TITLE
Issue installing Sharp from Github Actions and deploying to AWS Lambda

### ISSUE THREAD

**Issue by RBrNx** [lovell/sharp#2747]
_Did you see the [documentation relating to installation](https://sharp.pixelplumbing.com/install)?_
Yes I have followed it

_Have you ensured the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime?_
Yes, both using Node 14

_Are you using the latest version? Is the version currently in use as reported by `npm ls sharp` the same as the latest version as reported by `npm view sharp dist-tags.latest`?_
Yes, both are version 0.28.3

What is the complete output of running `npm install --verbose sharp`? Have you checked this output for useful error messages?
Output was massive so I put it [into a gist](https://gist.github.com/RBrNx/70660c80cbfa22eec999fe66b7247786)

What is the output of running `npx envinfo --binaries --system`?
```
  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 4.22 GB / 6.79 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.0 - /opt/hostedtoolcache/node/14.17.0/x64/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /opt/hostedtoolcache/node/14.17.0/x64/bin/npm
```
------------------------------------------

I am trying to create an AWS Lambda function that uses `sharp` to resize images in S3. My setup is using the [Serverless framework](https://www.serverless.com/) to deploy my lambda code and I am using Yarn as my package manager. Following the installation docs I ended up with the following:

serverless.yml
```
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      nodeModulesRelativeDir: '../'
    packager: 'yarn'
```

webpack.config.js
```js
const nodeExternals = require('webpack-node-externals');

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  // Generate sourcemaps for proper error messages
  devtool: 'source-map',
  // Since 'aws-sdk' is not compatible with webpack,
  // we exclude all node dependencies
  externals: [nodeExternals(), { saslprep: 'saslprep', sharp: 'commonjs sharp' }],
  ...
};
```

I initially struggled to install the correct version of sharp, as Yarn seems to have issues using the `--arch` and `--platform` flags (#2340) but I was able to get it to install the correct version locally by adding the `.npmrc` file discussed in that post and running `yarn add sharp`. This solution seems to work great when I run `sls deploy` on my local machine - my lambdas deploy and work as intended.

However when I attempt to deploy my lambdas via a Github Action, the above solution no longer seems to work. Attempting to invoke my lambda will result in `'linuxmusl-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'linux-x64' platform.` - which suggests perhaps the `.npmrc` is being ignored? My workflow is as follows:

```
name: Deploy API (Development)

on:
  push:
    branches:
      - develop
    paths:
      - 'wedding-api/**'
      - '.github/workflows/deploy-api-dev.yml'
defaults:
  run:
    working-directory: ./wedding-api
jobs:
  deploy:
    name: Deploy Dev API
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install modules
        run: yarn
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: -c "cd wedding-api && serverless deploy --stage=dev --verbose"
          entrypoint: /bin/sh
```

I think my problem probably stems from the difficulty of getting Yarn to install the correct version compared to npm, but I'm hoping that changing package manager is a last resort.
