### ISSUE TITLE
Install/build performance when using in GitHub Actions

### ISSUE THREAD

**Issue by jyooru** [lovell/sharp#2768]
**What are you trying to achieve?**

I have a project that uses this library. It has CI setup on GitHub Actions, and I would like to shorten the time it takes for the Action to install this dependency. It only downloads and installs dependencies that aren't cached in `~/.npm`. The runner appears to be caching `libvips` but still compiles `sharp` on each run.

The logs (below) mention `No prebuilt binaries found (target=14.17.1 runtime=node arch=x64 libc= platform=linux)`. How can I build this package for the runner and get it to install that prebuilt package, instead of compiling it on each run?

**Have you searched for similar questions?**

Yes

**Are you able to provide a minimal, standalone code sample that demonstrates this question?**

Workflow 
```yaml
      - name: Cache Node dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Node dependencies
        run: npm install
```

Logs
```> sharp@0.23.4 install /home/runner/work/website/website/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Using cached /home/runner/.npm/_libvips/libvips-8.8.1-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.17.1 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/home/runner/work/website/website/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
  CXX(target) Release/obj.target/sharp/src/metadata.o
  CXX(target) Release/obj.target/sharp/src/stats.o
  CXX(target) Release/obj.target/sharp/src/operations.o
  CXX(target) Release/obj.target/sharp/src/pipeline.o
  CXX(target) Release/obj.target/sharp/src/sharp.o
  CXX(target) Release/obj.target/sharp/src/utilities.o
  SOLINK_MODULE(target) Release/obj.target/sharp.node
  COPY Release/sharp.node
make: Leaving directory '/home/runner/work/website/website/node_modules/sharp/build'
```

**Are you able to provide a sample image that helps explain the question?**

Not much else apart from the logs above.
