### ISSUE TITLE
gatsby-starter-developer-diary repo has outdated dependencies

### ISSUE THREAD

**Issue by Amila-Rukshan** [lovell/sharp#3193]
I'm also facing this issue where sharp is a transitive dependency in the [gatsby blog theme](https://github.com/willjw3/gatsby-starter-developer-diary). 
`npm ERR! ERR! sharp Use with glibc 2.28 requires manual installation of libvips >= 8.10.5`
I'm going to deploy this on [raspberry Pi 4](https://www.raspberrypi.com/products/raspberry-pi-4-model-b/specifications/) which is ARM v8 - 64 bit. And I'm doing the building in github actions as platform set to linux/arm64.
Following is the Dockerfile I have.
```
FROM node:16.4.2 as builder

WORKDIR /app

COPY package.json .
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build

FROM nginx
EXPOSE 80
COPY --from=builder /app/public /usr/share/nginx/html
```
Github action
```
name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/dev-diary:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/dev-diary:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/dev-diary:buildcache,mode=max
```
 it builds successfully when only `linux/amd64` is set as the platform
 
I think I should use this in the docker pipeline  https://github.com/lovell/sharp-libvips/blob/main/linux-arm64v8/Dockerfile
But I'm not sure what to copy and where to copy at node level step.

Home someone could guide me to sort this out. Thanks in advance!
