### ISSUE TITLE
Cannot find module '../build/Release/sharp-linuxmusl-arm64v8.node' on docker alpine

### ISSUE THREAD

**Issue by cyango** [lovell/sharp#3830]
Im having this error not matter what i try: Cannot find module '../build/Release/sharp-linuxmusl-arm64v8.node'

This is my docker file:

```
FROM node:18-alpine as buildStage

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

RUN apk update
RUN apk add ffmpeg

COPY . ./

COPY src/emails ./build/emails

RUN npm install --ignore-scripts=false

FROM node:18-alpine AS targetStage

COPY --from=buildStage . .

WORKDIR /app

CMD npm run start_local
```

This is my dockerignore

```
.git/
.gitignore
**/.DS_Store
.next/
.dockerignore
docker-compose.yaml
node_modules
README.md
.vscode
build
devOps/kubernetes
devOps/docker

```

This is my docker compose
```

version: '3.8'
services:
  cyango-worker:
    container_name: cyango-worker
    # network_mode: 'host'
    build:
      context: ./
      target: targetStage
      dockerfile: ./devOps/docker/Dockerfile.dev
    volumes:
      - ./:/app:delegated
    networks:
      - cyango-worker-network
    logging:
      driver: local
      options:
        max-size: '10m'
        max-file: '3'
```

I've tried

npm install --arch=arm64 --platform=linux --libc=musl sharp

and many other attempts i found on google. Don't know what to do anymore.

## Possible install-time or require-time problem

- [x ] I have read the [documentation relating to installation](https://sharp.pixelplumbing.com/install).
- [ x] I have ensured that the architecture and platform of Node.js used for `npm install` is the same as the architecture and platform of Node.js used at runtime.

### Are you using the latest version of sharp?
- 0.32.6
