### ISSUE TITLE
How to install sharp library in Github withastro/action and Bun

### ISSUE THREAD

**Issue by GasparSukk** [lovell/sharp#3852]
## Question about an existing feature

How to add `sharp` module in Github Actions?

### What are you trying to achieve?

Would like to build [Astro](https://astro.build) (static) site with `astro build` in Github Actions.
Using `astro-compress` package (uses `sharp` library).

### Part of my package.json
```json
{
  "dependencies": {
    "astro": "^3.3.2",
    "astro-compress": "^2.2.3",
  },
  "private": true,
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "type": "module"
}
```

### My build.yml file:

```yml
name: Build

on:
    push:
        branches: [ main ]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout your repository using git
              uses: actions/checkout@v3
            - name: Build it
              uses: withastro/action@v1
```

### Error during the build:
```log
Run cd .
$ astro build
[vite] Error when evaluating SSR module /home/runner/work/[redacted]/astro.config.mjs: failed to import "astro-compress"
|- Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-linux-x64.node'
```

#### What i am missing here?
