### ISSUE TITLE
pnpm@10 blocks lifecycle scripts by default, causing sharp not to build

### ISSUE THREAD

**Issue by aiktb** [lovell/sharp#4343]
When I use pnpm@10, I find that there is no `build` directory in node_modules/sharp, and any command reports an error "Cannot find module '../build/Release/sharp-darwin-arm64v8.node'"

This is different from all the issues mentioned in the sharp installation documentation. 

This is not a sharp bug, but it took me hours to find it, so it's worth noting. 

Feel free to close this.

Solution:
Downgrade to pnpm@9
or modify package.json:
```json
{
  "pnpm": {
    "onlyBuiltDependencies": ["sharp"]
  }
}
```

**Comment by lovell** [comment]
Are you using the latest version of sharp?

**Comment by aiktb** [comment]
> Are you using the latest version of sharp?

Yes

**Comment by lovell** [comment]
Thanks, I've add a note about this to the docs via commit https://github.com/lovell/sharp/commit/a619f293134763079754545b4bf5b8e265a9e1ee

**Comment by kachkaev** [comment]
> you may need to add `sharp` 

Would it be possible to clarify in which situations it is necessary to set `onlyBuiltDependencies`? If I understand correctly, a corresponding binary gets installed via optional dependencies unless optional dependencies are explicitly turned off. So my intuition is to add `sharp` to [`ignoredBuiltDependencies`](https://pnpm.io/package_json#pnpmignoredbuiltdependencies) instead of `onlyBuiltDependencies`. Assuming that pnpm config is shared between all contributors and everyone is on a more or less recent OS, I don’t see a case when `install/check` will ever be needed. Please correct me if I'm wrong.

**Comment by kachkaev** [comment]
Adding a note to installation docs would be awesome! Being able to annotate the decision in `pnpm-workspace.yaml` would be ideal:

```yaml
ignoredBuiltDependencies:
  - sharp ## https://url-to-sharp-docs-that-justifies-the-decision
  - ... ## https://url-to-docs-that-justifies-the-decision

onlyBuiltDependencies:
  - ... ## https://url-to-docs-that-justifies-the-decision
```
