### ISSUE TITLE
sRGB images and hasAlpha

### ISSUE THREAD

**Issue by salzhrani** [lovell/sharp#526]
currently getting `metadata` of an `sRGB` image returns that it has four channels, and this is maybe why the `hasAlpha` check [here](https://github.com/lovell/sharp/blob/c42fb97419231452fefe4b9079264e3e2e6aeaf8/src/common.cc#L168) returns `true`.
here is a log
```
metadata { format: 'png',
  width: 315,
  height: 315,
  space: 'srgb',
  channels: 4,
  density: 72,
  hasProfile: true,
  hasAlpha: true,
  icc: <Buffer 0 ...
}
```

**Comment by lovell** [comment]
Hello, this looks like the output I'd expect for an sRGB PNG image that contains an alpha transparency layer (the four channels are red, green, blue and alpha). Does this match with the image you're using?

**Comment by salzhrani** [comment]
after checking it seems that it has an alpha channel, but no transparency. I guess I conflated alpha with transparency. any advice on how to check for transparency besides the obvious loop over each pixel?

here is the output of `identify`:
```yml
identify -verbose /Users/samy/Desktop/H1g9uVzu.png
Image: /Users/samy/Desktop/H1g9uVzu.png
  Format: PNG (Portable Network Graphics)
  Mime type: image/png
  Class: DirectClass
  Geometry: 315x315+0+0
  Resolution: 28.34x28.34
  Print size: 11.115x11.115
  Units: PixelsPerCentimeter
  Type: TrueColorAlpha
  Endianess: Undefined
  Colorspace: sRGB
  Depth: 8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
    alpha: 1-bit
  Channel statistics:
    Pixels: 99225
    Red:
      min: 0 (0)
      max: 255 (1)
      mean: 114.721 (0.449885)
      standard deviation: 64.9489 (0.254701)
      kurtosis: -0.733505
      skewness: 0.424506
      entropy: 0.94251
    Green:
      min: 0 (0)
      max: 255 (1)
      mean: 125.446 (0.491944)
      standard deviation: 64.7183 (0.253797)
      kurtosis: -0.719933
      skewness: -0.111517
      entropy: 0.938506
    Blue:
      min: 0 (0)
      max: 255 (1)
      mean: 154.604 (0.606289)
      standard deviation: 73.6238 (0.288721)
      kurtosis: -0.910429
      skewness: -0.650536
      entropy: 0.945023
    Alpha:
      min: 255 (1)
      max: 255 (1)
      mean: 255 (1)
      standard deviation: 0 (0)
      kurtosis: 0
      skewness: 0
      entropy: 0
  Image statistics:
    Overall:
      min: 0 (0)
      max: 255 (1)
      mean: 98.6925 (0.387029)
      standard deviation: 58.7947 (0.230567)
      kurtosis: 3.67942
      skewness: 0.629073
      entropy: 0.70651
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: white
  Border color: srgba(223,223,223,1)
  Matte color: grey74
  Transparent color: none
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 315x315+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: Zip
  Orientation: Undefined
  Properties:
    date:create: 2016-07-24T16:00:50+03:00
    date:modify: 2016-07-24T15:58:38+03:00
    png:iCCP: chunk was found
    png:IHDR.bit-depth-orig: 8
    png:IHDR.bit_depth: 8
    png:IHDR.color-type-orig: 6
    png:IHDR.color_type: 6 (RGBA)
    png:IHDR.interlace_method: 0 (Not interlaced)
    png:IHDR.width,height: 315, 315
    png:pHYs: x_res=2834, y_res=2834, units=1
    signature: 551fda4b6b84eecff094d9b4d22f946e9ef540c0fe85d55679e78fdbb4d073d9
  Profiles:
    Profile-icc: 2428 bytes
  Artifacts:
    filename: /Users/samy/Desktop/H1g9uVzu.png
    verbose: true
  Tainted: False
  Filesize: 145KB
  Number pixels: 99.2K
  Pixels per second: 9.923MB
  User time: 0.000u
  Elapsed time: 0:01.009
  Version: ImageMagick 6.9.3-6 Q16 x86_64 2016-02-28 http://www.imagemagick.org
```
